
/* pizza라는 스키마 생성*/
CREATE SCHEMA PIZZA;

/*pizza 스키마 사용*/
USE PIZZA;

############################ 테이블 생성 ##########################

CREATE TABLE CUSTOMER (
CUST_ID VARCHAR(20) NOT NULL,
CUST_PW VARCHAR(20) NOT NULL,
CUST_NAME VARCHAR(10) NOT NULL,
CUST_ADDR VARCHAR(100) NOT NULL,
CUST_CONTACT VARCHAR(15) NOT NULL,
CUST_EMAIL VARCHAR(50) NOT NULL,
CUST_TOTAL_PRICE INT NULL,
PRIMARY KEY (CUST_ID)
);

CREATE TABLE SHOP (
SHOP_ID VARCHAR(10) NOT NULL,
SHOP_NAME VARCHAR(20) NOT NULL,
SHOP_ADDR VARCHAR(100) NOT NULL,
SHOP_CONTACT VARCHAR(15) NOT NULL,
PRIMARY KEY (SHOP_ID)
);

CREATE TABLE MENU(
MENU_ID VARCHAR(10) NOT NULL,
MENU_TYPE INT NOT NULL, # 피자 : 1, 사이드 : 2, 토핑 : 3 
MENU_NAME varchar(20) NOT NULL,
MENU_PRICE INT NOT NULL,
MENU_SIZE varchar(2) NULL,
MENU_DESC VARCHAR(200) NULL,
primary key (MENU_ID)
);

CREATE TABLE TB_ORDER(
ORDER_ID VARCHAR(10) NOT NULL,
CUST_ID VARCHAR(20) NOT NULL,
SHOP_ID VARCHAR(10) NOT NULL,
ORDER_DATE DATE NOT NULL,
ORDER_ADDR VARCHAR(100) NOT NULL,
ORDER_PRICE int NOT NULL,
primary KEY (ORDER_ID),
foreign key (CUST_ID) references CUSTOMER(CUST_ID) ON DELETE cascade,
foreign key (SHOP_ID) references SHOP(SHOP_ID) ON DELETE  cascade
);

CREATE TABLE ORDER_DESC(
ORDER_ID VARCHAR(10) NOT NULL,
MENU_ID VARCHAR(10) NOT NULL,
NUM INT NOT NULL,
foreign key (ORDER_ID) references TB_ORDER(ORDER_ID) ON DELETE cascade,
foreign key (MENU_ID) references MENU(MENU_ID) ON DELETE  cascade
);


############### 데이터 삽입 ################
# 1. 회원정보
INSERT INTO CUSTOMER (CUST_ID, CUST_PW, CUST_NAME, CUST_ADDR, CUST_CONTACT, CUST_EMAIL, CUST_TOTAL_PRICE) 
				VALUES('encore', '1234', 'James', '서울시', '010-1234-1234', 'encore@gmail.com', 10000);
INSERT INTO CUSTOMER (CUST_ID, CUST_PW, CUST_NAME, CUST_ADDR, CUST_CONTACT, CUST_EMAIL, CUST_TOTAL_PRICE) 
				VALUES('play', '1234', 'Tom', '경기도', '010-3333-1234', 'play@gmail.com', 50000);
INSERT INTO CUSTOMER (CUST_ID, CUST_PW, CUST_NAME, CUST_ADDR, CUST_CONTACT, CUST_EMAIL) 
				VALUES('date', '1234', 'jack', '경기도', '010-3333-5555', 'data@gmail.com');
                
           
# 2. 가게정보          
INSERT INTO SHOP (SHOP_ID, SHOP_NAME, SHOP_ADDR, SHOP_CONTACT) 
			VALUES('k001', '수원점', '수원시', '031-123-2333'); 
INSERT INTO SHOP (SHOP_ID, SHOP_NAME, SHOP_ADDR, SHOP_CONTACT) 
			VALUES('S001', '서울 1호점', '서울시', '02-333-2222');
            
# 3. 메뉴

## 피자 추가
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_SIZE, MENU_DESC) 
			VALUES('P001-R', 1, '포테이토 피자 R', '15000', 'R', '포테이토 피자 R사이즈 입니다.'); 
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_SIZE, MENU_DESC) 
			VALUES('P001-L', 1, '포테이토 피자 L', '20000', 'L', '포테이토 피자 L사이즈 입니다.');
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_SIZE, MENU_DESC) 
			VALUES('P002-R', 1, '치즈 피자 R', '15000', 'R', '치즈 피자 R사이즈 입니다.'); 
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_SIZE, MENU_DESC) 
			VALUES('P002-L', 1, '치즈 피자 L', '20000', 'L', '치즈 피자 L사이즈 입니다.');
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_SIZE, MENU_DESC) 
			VALUES('P003-R', 1, '하와이안 피자 R', '15000', 'R', '하와이안 피자 R사이즈 입니다.'); 
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_SIZE, MENU_DESC) 
			VALUES('P003-L', 1, '하와이안 피자 L', '20000', 'L', '하와이안 피자 L사이즈 입니다.');    
## 사이드 추가
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_DESC) 
			VALUES('S001', 2, '콜라 1.5L', '2000',  '콜라 1.5L 입니다.'); 
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_DESC) 
			VALUES('S002', 2, '토마토 파스타', '5000', '토마토 파스타 입니다.');    
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_DESC) 
			VALUES('S003', 2, '로제 파스타', '5500', '로제 파스타 입니다.');

## 토핑 추가
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_DESC) 
			VALUES('T001', 3, '새우 토핑', '2000',  '새우 토핑 입니다.'); 
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_DESC) 
			VALUES('T002', 3, '스테이크 토핑', '2000', '스테이크 토핑 입니다.');    
INSERT INTO MENU (MENU_ID, MENU_TYPE, MENU_NAME, MENU_PRICE, MENU_DESC) 
			VALUES('T003', 3, '고구마 토핑', '2000', '고구마 토핑 입니다.');       
            
            